

Config.Containers = {}

Config.Containers.Rent = 2000
Config.Containers.FirstPayment = 5000
Config.Containers.TotalRent = 28000
Config.Containers.size = 800000
Config.Containers.slots = 20

Config.Containers.Capac = {
	[1] = {
		size = 1300000,
		slots = 35,
		price = 25000,
		money = 'bank'
	},
	[2] = {
		size = 1700000,
		slots = 45,
		price = 35000,
		money = 'bank'
	},
	[3] = {
		size = 2500000,
		slots = 55,
		price = 45000,
		money = 'bank',
	},
}

Config.Containers.Locations = {
	[1] = {
		id = 1,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.7, -2968.49, 5.9),
			name = '1',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 1,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[2] = {
		id = 2,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.77, -2971.22, 5.9),
			name = '2',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 2,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[3] = {
		id = 3,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.83, -2973.9, 5.9),
			name = '3',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 3,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[4] = {
		id = 4,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.8, -2976.53, 5.9),
			name = '4',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 4,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[5] = {
		id = 5,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.86, -2979.14, 5.9),
			name = '5',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 5,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[6] = {
		id = 6,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.83, -2995.17, 5.9),
			name = '6',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 6,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[7] = {
		id = 7,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.86, -2992.52, 5.9),
			name = '7',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 7,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[8] = {
		id = 8,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.85, -2989.92, 5.9),
			name = '8',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 8,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[9] = {
		id = 9,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.83, -2987.24, 5.9),
			name = '9',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 9,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[10] = {
		id = 10,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.79, -2984.55, 5.9),
			name = '10',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 10,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[11] = {
		id = 11,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.94, -2968.54, 5.9),
			name = '11',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 11,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[12] = {
		id = 12,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.93, -2971.2, 5.9),
			name = '12',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 12,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[13] = {
		id = 13,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(911.0, -2973.83, 5.9),
			name = '13',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 13,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[14] = {
		id = 14,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.9, -2976.47, 5.9),
			name = '14',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 14,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[15] = {
		id = 15,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.98, -2979.16, 5.9),
			name = '15',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 15,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[16] = {
		id = 16,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(922.9, -2995.16, 5.9),
			name = '16',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 16,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[17] = {
		id = 17,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(922.9, -2992.52, 5.9),
			name = '17',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 17,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[18] = {
		id = 18,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(922.94, -2989.86, 5.9),
			name = '18',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 18,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[19] = {
		id = 19,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.69, -2995.1, 5.9),
			name = '19',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 19,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[20] = {
		id = 20,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.68, -2992.46, 5.9),
			name = '20',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 20,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[21] = {
		id = 21,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.74, -2989.82, 5.9),
			name = '21',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 21,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[22] = {
		id = 22,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.72, -2987.2, 5.9),
			name = '22',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 22,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[23] = {
		id = 23,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.72, -2984.53, 5.9),
			name = '23',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 23,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[24] = {
		id = 24,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.98, -2979.14, 5.9),
			name = '24',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 24,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[25] = {
		id = 25,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(925.03, -2976.51, 5.9),
			name = '25',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 25,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[26] = {
		id = 26,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.97, -2973.87, 5.9),
			name = '26',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 26,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[27] = {
		id = 27,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.91, -2971.26, 5.9),
			name = '27',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 27,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[28] = {
		id = 28,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.9, -2968.63, 5.9),
			name = '28',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 28,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[29] = {
		id = 29,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(900.08, -3020.34, 5.9),
			name = '29',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 29,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[30] = {
		id = 30,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.83, -3023.66, 5.9),
			name = '30',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 30,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[31] = {
		id = 31,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.82, -3026.36, 5.9),
			name = '31',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 31,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[32] = {
		id = 32,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.86, -3028.94, 5.9),
			name = '32',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 32,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[33] = {
		id = 33,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.89, -3031.58, 5.9),
			name = '33',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 33,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[34] = {
		id = 34,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.83, -3047.44, 5.9),
			name = '34',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 34,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[35] = {
		id = 35,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.84, -3044.68, 5.9),
			name = '35',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 35,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[36] = {
		id = 36,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.86, -3039.53, 5.9),
			name = '36',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 36,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[37] = {
		id = 37,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.89, -3036.82, 5.9),
			name = '37',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 37,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[38] = {
		id = 38,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.93, -3039.66, 5.9),
			name = '38',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 38,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[39] = {
		id = 39,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.9, -3037.03, 5.9),
			name = '39',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 39,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[40] = {
		id = 40,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.89, -3031.59, 5.9),
			name = '40',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 40,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[41] = {
		id = 41,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.93, -3029.0, 5.9),
			name = '41',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 41,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[42] = {
		id = 42,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.93, -3026.3, 5.9),
			name = '42',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 42,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[43] = {
		id = 43,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.91, -3023.66, 5.9),
			name = '43',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 43,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[44] = {
		id = 44,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.93, -3021.09, 5.9),
			name = '44',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 44,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[45] = {
		id = 45,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.92, -2992.4, 5.9),
			name = '45',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 45,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[46] = {
		id = 46,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.91, -2995.01, 5.9),
			name = '46',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 46,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[47] = {
		id = 47,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.93, -3021.05, 5.9),
			name = '47',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 47,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[48] = {
		id = 48,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.85, -3023.64, 5.9),
			name = '48',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 48,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[49] = {
		id = 49,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.86, -3026.32, 5.9),
			name = '49',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 49,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[50] = {
		id = 50,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.91, -3028.97, 5.9),
			name = '50',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 50,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[51] = {
		id = 51,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.94, -3031.62, 5.9),
			name = '51',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 51,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[52] = {
		id = 52,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.9, -3037.52, 5.9),
			name = '52',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 52,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[53] = {
		id = 53,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.9, -3040.21, 5.9),
			name = '53',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 53,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[54] = {
		id = 54,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(922.92, -3042.3, 5.9),
			name = '54',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 54,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[55] = {
		id = 55,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(922.95, -3044.93, 5.9),
			name = '55',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 55,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[56] = {
		id = 56,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.92, -3044.96, 5.9),
			name = '56',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 56,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[57] = {
		id = 57,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(924.76, -3047.63, 5.9),
			name = '57',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 57,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[58] = {
		id = 58,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(922.95, -3047.6, 5.9),
			name = '58',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 58,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[59] = {
		id = 59,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.66, -3047.59, 5.9),
			name = '59',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 59,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[60] = {
		id = 60,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.69, -3044.97, 5.9),
			name = '60',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 60,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[61] = {
		id = 61,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.73, -3042.24, 5.9),
			name = '61',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 61,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[62] = {
		id = 62,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.75, -3039.64, 5.9),
			name = '62',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 62,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[63] = {
		id = 63,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.73, -3037.08, 5.9),
			name = '63',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 63,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[64] = {
		id = 64,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.93, -3031.57, 5.9),
			name = '64',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 64,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[65] = {
		id = 65,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.95, -3028.93, 5.9),
			name = '65',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 65,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[66] = {
		id = 66,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.91, -3026.36, 5.9),
			name = '66',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 66,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[67] = {
		id = 67,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(938.95, -3023.66, 5.9),
			name = '67',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 67,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[68] = {
		id = 68,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(939.09, -3021.04, 5.9),
			name = '68',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 68,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[69] = {
		id = 69,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(952.96, -3021.02, 5.9),
			name = '69',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 69,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[70] = {
		id = 70,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(952.95, -3023.68, 5.9),
			name = '70',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 70,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[71] = {
		id = 71,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(952.93, -3026.28, 5.9),
			name = '71',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 71,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[72] = {
		id = 72,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(952.94, -3028.95, 5.9),
			name = '72',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 72,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[73] = {
		id = 73,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(952.89, -3031.58, 5.9),
			name = '73',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 73,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[74] = {
		id = 74,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.69, -3036.91, 5.9),
			name = '74',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 74,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[75] = {
		id = 75,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.65, -3039.54, 5.9),
			name = '75',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 75,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[76] = {
		id = 76,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.66, -3042.19, 5.9),
			name = '76',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 76,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[77] = {
		id = 77,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.65, -3044.84, 5.9),
			name = '77',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 77,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[78] = {
		id = 78,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.65, -3047.55, 5.9),
			name = '78',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 78,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[79] = {
		id = 79,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.75, -2995.21, 5.9),
			name = '79',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 79,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[80] = {
		id = 80,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.75, -2992.53, 5.9),
			name = '80',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 80,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[81] = {
		id = 81,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.76, -2989.94, 5.9),
			name = '81',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 81,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[82] = {
		id = 82,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.75, -2987.25, 5.9),
			name = '82',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 82,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[83] = {
		id = 83,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.79, -2984.66, 5.9),
			name = '83',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 83,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[84] = {
		id = 84,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.95, -2978.8, 5.9),
			name = '84',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 84,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[85] = {
		id = 85,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.9, -2976.22, 5.9),
			name = '85',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 85,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[86] = {
		id = 86,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.94, -2973.54, 5.9),
			name = '86',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 86,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[87] = {
		id = 87,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.92, -2970.93, 5.9),
			name = '87',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 87,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[88] = {
		id = 88,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(964.95, -2968.27, 5.9),
			name = '88',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 88,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[89] = {
		id = 89,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(950.92, -2968.35, 5.9),
			name = '89',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 89,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[90] = {
		id = 90,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(950.88, -2970.95, 5.9),
			name = '90',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 90,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[91] = {
		id = 91,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(950.92, -2973.56, 5.9),
			name = '91',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 91,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[92] = {
		id = 92,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(950.9, -2976.23, 5.9),
			name = '92',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 92,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[93] = {
		id = 93,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(818.48, -3074.58, 5.9),
			name = '93',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 93,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[94] = {
		id = 94,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(817.59, -3077.33, 5.9),
			name = '94',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 94,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[95] = {
		id = 95,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(817.56, -3079.94, 5.9),
			name = '95',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 95,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[96] = {
		id = 96,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(817.52, -3082.59, 5.9),
			name = '96',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 96,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[97] = {
		id = 97,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(817.6, -3085.22, 5.9),
			name = '97',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 97,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[98] = {
		id = 98,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(831.66, -3074.73, 5.9),
			name = '98',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 98,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[99] = {
		id = 99,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(831.64, -3077.34, 5.9),
			name = '99',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 99,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[100] = {
		id = 100,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(831.67, -3079.96, 5.9),
			name = '100',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 100,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[101] = {
		id = 101,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(831.7, -3082.58, 5.9),
			name = '101',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 101,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[102] = {
		id = 102,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(831.64, -3085.24, 5.9),
			name = '102',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 102,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[103] = {
		id = 103,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(831.65, -3090.65, 5.9),
			name = '103',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 103,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[104] = {
		id = 104,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(831.66, -3093.27, 5.9),
			name = '104',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 104,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[105] = {
		id = 105,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(829.53, -3090.56, 5.9),
			name = '105',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 105,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[106] = {
		id = 106,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(829.58, -3093.19, 5.9),
			name = '106',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 106,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[107] = {
		id = 107,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(829.6, -3098.86, 5.9),
			name = '107',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 107,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[108] = {
		id = 108,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(829.65, -3101.52, 5.9),
			name = '108',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 108,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[109] = {
		id = 109,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(845.63, -3101.66, 5.9),
			name = '109',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 109,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[110] = {
		id = 110,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(845.65, -3093.17, 5.9),
			name = '110',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 110,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[111] = {
		id = 111,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(845.61, -3090.53, 5.9),
			name = '111',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 111,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[112] = {
		id = 112,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(843.63, -3095.93, 5.9),
			name = '112',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 112,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[113] = {
		id = 113,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(843.65, -3098.57, 5.9),
			name = '113',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 113,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[114] = {
		id = 114,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(843.63, -3101.16, 5.9),
			name = '114',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 114,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[115] = {
		id = 115,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.46, -3101.19, 5.9),
			name = '115',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 115,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[116] = {
		id = 116,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.44, -3098.59, 5.9),
			name = '116',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 116,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[117] = {
		id = 117,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.43, -3095.94, 5.9),
			name = '117',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 117,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[118] = {
		id = 118,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.44, -3093.29, 5.9),
			name = '118',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 118,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[119] = {
		id = 119,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.42, -3090.7, 5.9),
			name = '119',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 119,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[120] = {
		id = 120,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.6, -3085.27, 5.9),
			name = '120',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 120,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[121] = {
		id = 121,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.61, -3082.58, 5.9),
			name = '121',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 121,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[122] = {
		id = 122,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.61, -3079.94, 5.9),
			name = '122',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 122,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[123] = {
		id = 123,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.65, -3077.27, 5.9),
			name = '123',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 123,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[124] = {
		id = 124,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(859.46, -3074.65, 5.9),
			name = '124',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 124,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[125] = {
		id = 125,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.77, -3074.61, 5.9),
			name = '125',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 125,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[126] = {
		id = 126,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.88, -3077.46, 5.9),
			name = '126',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 126,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[127] = {
		id = 127,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.88, -3080.11, 5.9),
			name = '127',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 127,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[128] = {
		id = 128,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(896.89, -3082.71, 5.9),
			name = '128',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 128,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[129] = {
		id = 129,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(909.01, -3101.3, 5.9),
			name = '129',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 129,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[130] = {
		id = 130,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(909.01, -3098.75, 5.9),
			name = '130',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 130,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[131] = {
		id = 131,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(909.0, -3096.07, 5.9),
			name = '131',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 131,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[132] = {
		id = 132,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.91, -3093.32, 5.9),
			name = '132',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 132,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[133] = {
		id = 133,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(908.89, -3090.73, 5.9),
			name = '133',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 133,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[134] = {
		id = 134,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.88, -3093.44, 5.9),
			name = '134',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 134,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[135] = {
		id = 135,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.94, -3090.81, 5.9),
			name = '135',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 135,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[136] = {
		id = 136,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.92, -3085.45, 5.9),
			name = '136',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 136,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[137] = {
		id = 137,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.88, -3082.8, 5.9),
			name = '137',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 137,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[138] = {
		id = 138,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.88, -3080.15, 5.9),
			name = '138',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 138,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[139] = {
		id = 139,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.9, -3077.53, 5.9),
			name = '139',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 139,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
	[140] = {
		id = 140,
		isOwned = false,
		Owner = nil,
		Total = 0,
		KeyHolders = {},
		stash = {
			coords = vector3(910.89, -3074.83, 5.9),
			name = '140',
			heading = 0,
			debugPoly= false,
			info1 = 2.0,
			info2 = 0.4,
			minZ=4.7,
			maxZ=7.3,
			options = {
				{ 
					type = "client", 
					icon = 'fa-solid fa-box',
					event = "qb-containers:client:ContainerMenu",  
					label = 'Container', 
					id = 140,
				}
			},
			distance = 1.0, 
			size = 800000,
			slots = 20,
		},
	},
}
